[package]
name = "tachyon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rusqlite = "0.31.0"

[dev-dependencies]
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "read"
harness = false

[[bench]]
name = "write"
harness = false

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

[profile.bench]
codegen-units = 1
opt-level = 3
lto = "fat"
