[workspace]
members = ["tachyon_core", "tachyon_cli"]
resolver = "2"

[profile.dev]
lto = "off"
opt-level = 0

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3

[profile.bench]
inherits = "release"
debug = "full"
