[package]
name = "tachyon_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
csv = "1.3.0"
prettytable-rs = "0.10.0"
rustyline = "14.0.0"
tachyon_core = { path = "../tachyon_core" }
textplots = "0.8.6"
