[package]
name = "tachyon_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }

[build-dependencies]
cbindgen = "0.26.0"
