name: Rust

on: push
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Run Format
        run: cargo fmt --all --check
      - name: Build
        run: cargo build --locked --verbose
      - name: Run Clippy
        # Make sure CI fails on all warnings
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: Run Tests
        run: cargo test --locked --verbose
