on: push
name: Rust

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Check Format
        run: cargo fmt --check
      - name: Build
        run: cargo build --release --verbose
      - name: Run Clippy
        # Make sure CI fails on all warnings, including Clippy lints
        run: cargo clippy --release --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --release --verbose
      - name: Run C test
        run: |
          cd ./scripts/c/
          chmod +x ./run.sh
          ./run.sh
        shell: bash
